version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - web-variables.env
    ports:
      - "8080:8080"
    command: mix run --no-halt
    volumes:
      - .:/opt/project_b
